### ISSUE TITLE
ValueError: Can't normalize Vector of length Zero

### ISSUE THREAD

**Issue by simsimiSION** [opendilab/GoBigger#20]
`
File "/gobigger/balls/clone_ball.py", line 152, in move
     self.direction = (self.vel + self.vel_last).normalize()
`

**Comment by mingzhang96** [comment]
Thanks for your issue! I check the related code:
```
if self.vel.length() > 0 or self.vel_last.length() > 0:
    self.direction = (self.vel + self.vel_last).normalize()
```
This error may be caused by the situation that `(self.vel + self.vel_last).length == 0`. We can prevent this by adding more judgments.
