### ISSUE TITLE
Is there any related benchmarks?

### ISSUE THREAD

**Issue by GEYOUR** [opendilab/GoBigger#40]
I knew there was a competition on this environment, so I wonder if there are some benchmark results using latest algorithms, or papers experimented on this environment such that comparisons can be made, thanks!

**Comment by mingzhang96** [comment]
For now you can find the benchmark result on [GoBigger-Explore](https://github.com/opendilab/Gobigger-Explore).  We have implemented some algorithms and more results will be published in that repo. Our paper is also in progress, and we will publish it when it is ready.
